#! /bin/sh
################





pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config normal_border_color           "#4c566a"
bspc config active_border_color	      "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"
bspc config window_gap          9
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config pointer_modifier	super






bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a qutebrowser desktop='^2' follow=true
bspc rule -a TelegramDesktop desktop='^3' follow=true
bspc rule -a Emacs desktop='^1' follow=true floating=off
bspc rule -a Albion Online Launcher desktop='^5' follow=true



nitrogen --restore &
polybar &

#setxkbmap -option grp:alt_shift_toggle us,ru &

